# Not that we depend on this, but otherwise it seems that the default
# language is Ruby!
language: c

sudo: true

notifications:
  email: false

addons:
  apt:
    packages:
    - build-essential
    - nasm
    - qemu-system-x86
    - python3
    - gcc-multilib

before_script:
- cd http && python3 -m http.server 8080 &

script:
- sudo cat /proc/cpuinfo
- sudo modprobe kvm
- make
- sudo qemu-system-i386 -hda build/boot_asmg.x86 -serial stdio -device isa-debug-exit -display none -m 256M -enable-kvm | ./test/decode_tests.py
- ls -l build/asmg.x86.exe build/asmg_dbg.x86.exe
